#!/Library/Frameworks/Python.framework/Versions/3.13/bin/python3

import logging
import os
from typing import Any, List

from mcp.server.fastmcp import FastMCP
from pycti import OpenCTIApiClient # https://github.com/OpenCTI-Platform/client-python/tree/master/examples

NAME = "opencti-mcp"

mcp = FastMCP(NAME)
OPENCTI_URL = os.environ.get("OPENCTI_URL")
OPENCTI_KEY = os.environ.get("OPENCTI_KEY")
opencti = OpenCTIApiClient(OPENCTI_URL, OPENCTI_KEY)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(NAME)



@mcp.tool()
async def search_observables(value: str) -> List[Any]:
    """
    Name: search_observables
    Description: Returns information about a named observable or indicator (e.g. IP address, domain name, file hash, etc)
    Parameters:
    value (required): The observable or indicator to search for
    """
    data = opencti.stix_cyber_observable.list(search=value)
    return data


@mcp.tool()
async def search_intrusion_sets(threat_actor: str) -> List[Any]:
    """
    Name: search_intrusion_sets
    Description: Returns information about a named threat actor
    Parameters:
    threat_actor (required): The name of the threat actor to search for
    """

    data = opencti.intrusion_set.read(
        filters={
            "mode": "and",
            "filters": [{"key": "name", "values": [threat_actor]}],
            "filterGroups": [],
        }
    )
    return data

@mcp.tool()
async def get_malware_for_intrusion_set(threat_actor: str) -> List[Any]:
    """
    Name: get_malware_for_intrusion_set
    Description: Returns information about the malware indicators used by a named threat actor
    Parameters:
    threat_actor (required): The name of the threat actor to search for
    """
    intrusion_set = opencti.intrusion_set.list(name=threat_actor)[0]
    if not intrusion_set:
        return []
    data = opencti.stix_core_relationship.list(
        fromId=intrusion_set["id"], toTypes=["Malware"]
    )
    return data 

@mcp.tool()
async def get_latest_reports(num: int = 10) -> List[Any]:
    """
    Name: get_latest_reports
    Description: Returns information about the latest num reports
    Parameters:
    num (required): The number of reports to return (default: 10)
    """
    custom_attributes = """
        id
        name
        published
        description
        """
    data = opencti.report.list(first=num, orderby="created_at", customAttributes=custom_attributes, orderMode="desc")
    return data

@mcp.tool()
async def get_reports_for_threat_actor(threat_actor: str) -> List[Any]:
    """
    Name: get_reports_for_threat_actor
    Description: Returns information about the reports generated by a named threat actor
    Parameters:
    threat_actor (required): The name of the threat actor to search for
    """
    intrusion_set = opencti.intrusion_set.list(name=threat_actor)[0]
    if not intrusion_set:
        return []
    data = opencti.report.list(
        filters={
            "mode": "and",
            "filters": [{"key": "objects", "values": [intrusion_set["id"]]}],
            "filterGroups": [],
        },
        orderBy="published",
        orderMode="asc",
    )
    return [ {"report name": x['name'], "published": x['published'], "id": x['standard_id']} for x in data ]

@mcp.tool()
async def search_malware_families(malware_family: str) -> List[Any]:
    """
    Name: search_malware_families
    Description: Returns information about a named malware family
    Parameters:
    malware_family (required): The name of the malware family to search for
    """
    data = opencti.malware.list(name=malware_family)
    return data

@mcp.tool()
async def search_vulnerabilities(vulnerability: str) -> List[Any]:
    """
    Name: search_vulnerabilities
    Description: Returns information about a named vulnerability
    Parameters:
    vulnerability (required): The vulnerability term to search for - a CVE ID, a vendor, etc
    """
    data = opencti.vulnerability.list(name=vulnerability)
    return data


def main() -> None:
    logger.info("Starting OpenCTI MCP server")
    mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
